version: '3.8'

services:
  merch-api:
    build: .
    hostname: merch-api
    ports:
      - "8080:80"
    
    depends_on:
      - emailing-service
      - stock-api
      - supply-service
      - employees-service
      
  merch-api-db:
    image: postgres:latest
    ports:
    - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchApiPassword
      POSTGRES_DB: merch-api
    command: "-c log_statement=all"
        
  emailing-service:
    image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
    hostname: emailing-service
    
  stock-api:
    image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
    hostname: stock-api
    
  supply-service:
    image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
    hostname: supply-service
    
  employees-service:
    image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
    hostname: employees-service

    
    